[build-system]
build-backend = "uv_build"
requires = [ "uv-build" ]

[project]
authors = [
    {name = "saveweb", email = "saveweb@saveweb.org"},
]
requires-python = "<4.0,>=3.10"
dependencies = [
    "motor>=3.7.1",
    "pymongo>=4.15.3",
]
name = "stwp-mongodb-helper"
version = "0.2.0"
description = ""
readme = "README.md"

[project.scripts]
grass_generator = "stwp_mongodb_helper.grass_generator:main"
grass_requeue = "stwp_mongodb_helper.grass_requeue:main"
grass_dedup = "stwp_mongodb_helper.grass_dedup:main"
